import { Kanit } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/notifications/styles.css";
import "mantine-datatable/styles.layer.css";
import { Notifications } from "@mantine/notifications";
import Navigation from "@/components/navbar/Navigation";
import Providers from "@/provider/Provider";
import { ColorSchemeScript } from "@mantine/core";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { getServerSession } from "next-auth/next";

const kanit = Kanit({
  subsets: ["latin"],
  variable: "--font-kanit",
  weight: "300",
});

export const metadata = {
  title: "Divider",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={kanit.className}>
        <Providers session={session}>
          <Navigation />
          <Notifications />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
